export default function TermsPage() {
  return (
    <main className="min-h-screen bg-[#F7F7FB] text-[#1F2937]">
      <section className="px-4 pt-24 pb-28 sm:px-6 sm:pt-28 sm:pb-32">
        <div className="mx-auto max-w-3xl space-y-10">
          <header className="space-y-3">
            <h1 className="font-serif text-2xl font-bold tracking-tight text-gray-900 sm:text-3xl">
              Terms of Use
            </h1>
            <p className="text-sm text-gray-500">
              These Terms of Use govern your access to and use of CreatorCalculators.com.
            </p>
          </header>

          <section aria-labelledby="acceptance-heading" className="space-y-3">
            <h2
              id="acceptance-heading"
              className="font-serif text-xl font-semibold text-gray-900"
            >
              Acceptance of terms
            </h2>
            <p className="text-base text-gray-700 leading-relaxed">
              By accessing or using CreatorCalculators.com (the &quot;Site&quot;), you agree to be
              bound by these Terms of Use. If you do not agree with these terms, you should not use
              the Site.
            </p>
          </section>

          <section aria-labelledby="informational-use-heading" className="space-y-3">
            <h2
              id="informational-use-heading"
              className="font-serif text-xl font-semibold text-gray-900"
            >
              Informational purpose and calculator estimates
            </h2>
            <p className="text-base text-gray-700 leading-relaxed">
              CreatorCalculators.com provides calculators and tools for creators, influencers, and
              marketers to estimate potential earnings, engagement, and growth across various
              platforms. The outputs generated by these tools are{" "}
              <strong>estimates only</strong>.
            </p>
            <p className="text-base text-gray-700 leading-relaxed">
              The Site and all calculators are provided for{" "}
              <strong>informational and educational purposes only</strong> and do not constitute
              financial, business, or legal advice. Actual results may differ significantly from any
              estimates shown.
            </p>
            <p className="text-base text-gray-700 leading-relaxed">
              You are solely responsible for how you interpret and use the information provided by
              the Site. You should always verify assumptions using your own data, platform
              analytics, and professional advice before making decisions.
            </p>
          </section>

          <section aria-labelledby="no-guarantees-heading" className="space-y-3">
            <h2
              id="no-guarantees-heading"
              className="font-serif text-xl font-semibold text-gray-900"
            >
              No guarantees or warranties
            </h2>
            <p className="text-base text-gray-700 leading-relaxed">
              CreatorCalculators.com is provided on an &quot;as is&quot; and &quot;as available&quot; basis.
              We make no representations or warranties of any kind, express or implied, regarding
              the accuracy, reliability, completeness, or availability of the Site or any results
              produced by the calculators.
            </p>
            <p className="text-base text-gray-700 leading-relaxed">
              To the fullest extent permitted by law, we disclaim all warranties, including any
              implied warranties of merchantability, fitness for a particular purpose, and
              non-infringement.
            </p>
          </section>

          <section aria-labelledby="limitation-heading" className="space-y-3">
            <h2
              id="limitation-heading"
              className="font-serif text-xl font-semibold text-gray-900"
            >
              Limitation of liability
            </h2>
            <p className="text-base text-gray-700 leading-relaxed">
              To the maximum extent permitted by law, CreatorCalculators.com and its owners shall
              not be liable for any direct, indirect, incidental, consequential, special, or
              exemplary damages arising out of or in connection with your use of the Site, the
              calculators, or any information provided, even if we have been advised of the
              possibility of such damages.
            </p>
            <p className="text-base text-gray-700 leading-relaxed">
              Your sole and exclusive remedy for dissatisfaction with the Site is to stop using it.
            </p>
          </section>

          <section aria-labelledby="user-responsibilities-heading" className="space-y-3">
            <h2
              id="user-responsibilities-heading"
              className="font-serif text-xl font-semibold text-gray-900"
            >
              Your responsibilities
            </h2>
            <p className="text-base text-gray-700 leading-relaxed">
              You agree to use CreatorCalculators.com in compliance with applicable laws and
              regulations. You also agree not to:
            </p>
            <ul className="list-disc pl-5 space-y-1 text-base text-gray-700 leading-relaxed">
              <li>Attempt to interfere with or disrupt the operation of the Site.</li>
              <li>Reverse engineer, scrape, or copy the Site in a way that violates applicable law.</li>
              <li>Use the Site for any unlawful or harmful purpose.</li>
            </ul>
          </section>

          <section aria-labelledby="third-party-heading" className="space-y-3">
            <h2
              id="third-party-heading"
              className="font-serif text-xl font-semibold text-gray-900"
            >
              Third-party services and links
            </h2>
            <p className="text-base text-gray-700 leading-relaxed">
              The Site may use or link to third-party services such as Google Analytics and Google
              AdSense, as well as other websites or resources. We do not control and are not
              responsible for the content, policies, or practices of any third-party services or
              websites.
            </p>
          </section>

          <section aria-labelledby="changes-heading" className="space-y-3">
            <h2
              id="changes-heading"
              className="font-serif text-xl font-semibold text-gray-900"
            >
              Changes to these terms
            </h2>
            <p className="text-base text-gray-700 leading-relaxed">
              We may update these Terms of Use from time to time. When we do, we will update the
              &quot;Terms of Use&quot; page on the Site. Your continued use of the Site after any
              changes become effective constitutes your acceptance of the updated terms.
            </p>
          </section>

          <section aria-labelledby="termination-heading" className="space-y-3">
            <h2
              id="termination-heading"
              className="font-serif text-xl font-semibold text-gray-900"
            >
              Termination
            </h2>
            <p className="text-base text-gray-700 leading-relaxed">
              We may suspend or terminate your access to CreatorCalculators.com at any time, for any
              reason, without prior notice, if we believe it is necessary to protect the Site, other
              users, or our rights.
            </p>
          </section>

          <section aria-labelledby="contact-heading" className="space-y-3">
            <h2
              id="contact-heading"
              className="font-serif text-xl font-semibold text-gray-900"
            >
              Contact
            </h2>
            <p className="text-base text-gray-700 leading-relaxed">
              If you have questions about these Terms of Use, you can contact us at{" "}
              <a
                href="mailto:contacts@creatorcalculators.com"
                className="text-blue-600 hover:underline break-all"
              >
                contacts@creatorcalculators.com
              </a>
              .
            </p>
          </section>
        </div>
      </section>
    </main>
  )
}
